# fly.toml app configuration file generated for mini-message-board-km on 2023-08-23T12:01:36-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mini-message-board-km"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
